### ISSUE TITLE
Some PDF documents cause pdftk 1.44 to loop forever

### ISSUE THREAD

**Issue by robinhouston** [robinhouston/pdftk#1]
The offending documents report a creator of “HP Digital Sending Device”. See https://github.com/mysociety/alaveteli/issues/305

Example document: http://www.whatdotheyknow.com/request/87534/response/234016/attach/12/HC9.pdf

**Comment by andreygursky** [comment]
I've checked the last 1.45 version. Upstream fixed this a little bit different. There is no infinite loop anymore, but after pdftotext HC9.pdf HC9.txt, HC9.txt contains some LFs (matching the page count I believe).

**Comment by wking** [comment]
On Sat, Jan 05, 2013 at 01:48:18PM -0800, andreygursky wrote:

> I've checked the last 1.45 version.

It's alive! _thunder/lightning/etc_

I've added v1.45 to my `history` and `master` branches and tagged them
[1](https://github.com/robinhouston/pdftk/issues).  This would be so much easier if Sid would respond to emails ;).

The last time I took a stab at porting `pdftk` from `lowagie` to it's
more actively maintained successor (`iText` [2](http://sourceforge.net/projects/itext/)), I was sunk by my
lack of Java knowledge and the variance among the assorted distro
patches.  Perhaps there will be more conformity in the patches based
on v1.45…

**Comment by robinhouston** [comment]
Thanks, everyone. I reckon we can skip this patch now, since 1.45 fixes the infinite loop. It looks like most of our other patches are still going to be needed, though.

I’m working on rebasing the other fixes against 1.45. I’m going to make a new branch here tracking wking’s master, and then base the patches on that. I’ll also move the OS X binary distribution to a separate branch.
